### ISSUE TITLE
No font file

### ISSUE THREAD

**Issue by IonicaBizau** [adros/git-stats-html#1]
I was running your tool and got this error:

``` sh
$ git-stats-html                                                                                                                                                            
fs.js:549                                                                                                                                                                                        
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);                                                                                                                   
                 ^                                                                                                                                                                               

Error: ENOENT: no such file or directory, open '/home/ionicabizau/.node/lib/node_modules/@gti/git-stats-html/lib/DejaVuSansMono.ttf'                                                             
    at Error (native)                                                                                                                                                                            
    at Object.fs.openSync (fs.js:549:18)                                                                                                                                                         
    at Object.fs.readFileSync (fs.js:397:15)                                                                                                                                                     
    at Object.<anonymous> (/home/ionicabizau/.node/lib/node_modules/@gti/git-stats-html/lib/index.js:21:42)                                                                                      
    at Module._compile (module.js:434:26)                                                                                                                                                        
    at Object.Module._extensions..js (module.js:452:10)                                                                                                                                          
    at Module.load (module.js:355:32)                                                                                                                                                            
    at Function.Module._load (module.js:310:12)                                                                                                                                                  
    at Module.require (module.js:365:17)                                                                                                                                                         
    at require (module.js:384:17)   
```

**Comment by adros** [comment]
hi, how did you find this :) ?
it was just a prototype, and actually we have given up this approach (even if it still seems to work, after committing the font file)
we are only using 'git-stats-data' (see bin), and then rendering it using https://github.com/kamisama/cal-heatmap

**Comment by IonicaBizau** [comment]
I noticed this repository somewhere on https://libraries.io and this is exactly what an issue in the main repo is about. Maybe you'd like to improve this tool. :smile: As of git-stats 2.0.0, things got improved and I will add soon a `--raw` option which will output some nice data you can parse as JSON, instead of parsing strings. :smile:
